github:
  description: "CommunityOverCode Website"
  homepage: https://communityovercode.apache.org/
  labels:
    - communityovercode
    - apachecon
    - asf
    - apache
    - test
  enabled_merge_buttons:
    squash: false
    merge: true
    rebase: false
  features:
    # Enable issue management
    issues: true
  pull_requests:
    del_branch_on_merge: true
notifications:
  commits:              notifications@conferences.apache.org
  pullrequests:         notifications@conferences.apache.org
  issues:               notifications@conferences.apache.org
