github:
  description: "CommunityOverCode Website"
  homepage: https://communityovercode.apache.org/
  labels:
    - communityovercode
    - apachecon
    - asf
    - apache
  enabled_merge_buttons:
    squash: false
    merge: true
    rebase: false
  features:
    # Enable issue management
    issues: true
  pull_requests:
    del_branch_on_merge: true
notifications:
  commits:              planners@apachecon.com
  pullrequests:         planners@apachecon.com
  issues:               planners@apachecon.com
